### ISSUE TITLE
MySQL Connection

### ISSUE THREAD

**Issue by Lapotor** [itpao25/ReporterGUI#2]
Ich benutze Craftbukkit 1.10.2 (Implementing API version 1.10.2-R0.1-SNAPSHOT)
```
[14:22:00] [pool-3-thread-9/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND status='OPEN'' at line 1
[14:22:00] [pool-3-thread-9/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:22:00] [pool-3-thread-9/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[14:22:00] [pool-3-thread-9/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[14:22:00] [pool-3-thread-9/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[14:22:00] [pool-3-thread-9/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
[14:22:00] [pool-3-thread-9/WARN]: 	at it.itpao25.NMSReport.q.c.g(MysqlReport.java:726)
[14:22:00] [pool-3-thread-9/WARN]: 	at it.itpao25.NMSReport.p.c.c(_Stats.java:57)
[14:22:00] [pool-3-thread-9/WARN]: 	at it.itpao25.NMSReport.a$1.run(Eventi.java:281)
[14:22:00] [pool-3-thread-9/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:53)
[14:22:00] [pool-3-thread-9/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:22:00] [pool-3-thread-9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:22:00] [pool-3-thread-9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:22:00] [pool-3-thread-9/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by itpao25** [comment]
You can try to set multi server on true?

**Comment by Lapotor** [comment]
ok
now it works
