### ISSUE TITLE
How can i fix this issue?

### ISSUE THREAD

**Issue by anonymous3ch0** [itpao25/ReporterGUI#3]
[09:09:42] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'PlayerFrom' in 'field list'
[09:09:42] [Server thread/WARN]: at sun.reflect.GeneratedConstructorAccessor247.newInstance(Unknown Source)
[09:09:42] [Server thread/WARN]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[09:09:42] [Server thread/WARN]: at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.Util.getInstance(Util.java:387)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:941)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3870)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3806)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2470)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2617)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2550)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
[09:09:42] [Server thread/WARN]: at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
[09:09:42] [Server thread/WARN]: at it.itpao25.NMSReport.q.e.<init>(MysqlReporterSegnalazione.java:70)
[09:09:42] [Server thread/WARN]: at it.itpao25.NMSReport.d.<init>(Segnalazione.java:105)
[09:09:42] [Server thread/WARN]: at it.itpao25.NMSReport.b.n.onCommand(CommandReportCLI.java:74)
[09:09:42] [Server thread/WARN]: at it.itpao25.NMSReport.b.a$a.execute(AbstractCommand.java:102)
[09:09:42] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[09:09:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[09:09:42] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[09:09:42] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[09:09:42] [Server thread/WARN]: at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[09:09:42] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by itpao25** [comment]
Try to create manually the field "PlayerFrom" in your db or try to regen the complete database (delete and restart the plugin)

**Comment by anonymous3ch0** [comment]
Worked, Thank you.
