### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by d5a** [itpao25/ReporterGUI#6]
We have enabled the Discord notifications, but the message is not sent to Discord and the following error occurs in the console:

```
[20:58:42 WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://discordapp.com/api/channels/xxxxxxxxxxxxxxxxx/messages
[20:58:42 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
[20:58:42 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[20:58:42 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[20:58:42 WARN]:        at it.itpao25.NMSReport.e.a.a(DiscordManager.java:175)
[20:58:42 WARN]:        at it.itpao25.NMSReport.b.<init>(Segnalazione.java:195)
[20:58:42 WARN]:        at it.itpao25.NMSReport.f.b.<init>(ListenerSlot.java:99)
[20:58:42 WARN]:        at it.itpao25.NMSReport.f.d.a(openGUI.java:116)
[20:58:42 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35)
[20:58:42 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[20:58:42 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:58:42 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1988)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[20:58:42 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:58:42 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[20:58:42 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[20:58:42 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by itpao25** [comment]
Hi, this error usually appears when the Discord token is not generated correctly
